const commander = require('commander');
const fs = require('fs');
const version = require('./package.json').version;

const template = version => `
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
export const VERSION = '${version}';
`.trim();

function readVersion(path, callback) {
  fs.readFile(path, 'utf8', (err, data) => {
    if (err) throw err;
    let json = JSON.parse(data);
    if (!json.hasOwnProperty('version'))
      throw new Error(`${path} doesn't contain version`);

    callback(json.version);
  });
}

function writeVersion(path, version, callback) {
  let data = template(version);
  fs.writeFile(path, data, err => {
    if (err) throw err;
    callback();
  });
}

commander
  .version(version)
  .description('A tiny command line tool that extract `package.json` version and generate `const VERSION=\'...\'` file')
  .usage('package.json src/version.js')
  .arguments("<package.json> <target_file>")
  .action((packageJSON, dest) => {
    readVersion(packageJSON, version => {
      writeVersion(dest, version, () => {
        console.log(version, 'done');
      })
    })
  })
  .parse(process.argv);
