const fs = require('fs')
const util = require('util')

const readFile = util.promisify(fs.readFile)
const writeFile = util.promisify(fs.writeFile)

const template = version =>
  '// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n' +
  `export const VERSION = '${version}';`

async function exec (source, dest) {
  const version = await _readVersion(source)
  await _writeVersion(dest, version)
}

async function _readVersion (source) {
  let data, json

  try {
    data = await readFile(source, 'utf8')
  } catch (e) {
    throw new Error('file not found')
  }

  try {
    json = JSON.parse(data)
  } catch (e) {
    throw new Error("file doesn't contain valid json")
  }

  if (!('version' in json)) {
    throw new Error('file doesn\'t contain version')
  }

  return json.version
}

async function _writeVersion (path, version) {
  const data = template(version)
  await writeFile(path, data)
}

module.exports = exec
